
import { Navigation } from "@/components/layout/Navigation";
import { Footer } from "@/components/layout/Footer";

export const metadata = {
    title: "Terms of Service | Teeko",
    description: "Terms of Service for Teeko AI"
};

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white dark:bg-gray-900 flex flex-col">
            <Navigation forceSolid />
            <main className="flex-grow pt-24 pb-16">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                    <h1 className="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-8">Terms & Conditions</h1>

                    <div className="prose prose-lg dark:prose-invert max-w-none space-y-6 text-gray-700 dark:text-gray-300">
                        <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Terms of Service</h2>

                        <p>If you are under the age of 18 or the legal age for giving consent hereunder pursuant to the applicable laws in your country (“legal age”), you must obtain permission from your parent(s) or legal guardian(s) to open an account on the Site. If you are the parent or legal guardian of a minor who is creating an account, you must accept and comply with these Terms of Use on the minor's behalf and you will be responsible for the minor’s actions, any charges associated with the minor’s use of the Site and/or Services or purchases made on the Site. If you do not have consent from your parent(s) or legal guardian(s), you must stop using and/or accessing this Site and/or Services.</p>

                        <p>Please read this Teeko’s terms of use (“Terms of use”) before downloading Teeko or accessing Teeko’s Web (which is referring to “Teeko AI”). These terms of use govern your use of the Teeko App and Teeko web subject to the Teeko Service Agreement and our privacy notice which are made available at https://teeko.ai. By entering, connecting to, accessing or using the Service, you acknowledge that you have read and understood the following terms and conditions, including the terms of our Privacy Notice available at Teeko/privacy website and you are agree to be bound by them and to comply with all applicable laws and regulations regarding your use of the Services and you acknowledge that these Terms constitute a binding and enforceable legal contract between Teeko, Asia Success Resources and you. These Terms of Service are a legally binding contract between you and Teeko regarding your use of the Service.</p>

                        <p className="font-bold uppercase">IF YOU DO NOT AGREE TO THESE TERMS, PLEASE DO NOT, CONNECT, ACCESS, DOWNLOAD, OR USE THE SERVICE IN ANY MANNER.</p>

                        <p>By acceptance of the Terms, you represent that any and all information you provide us through the Service is true and accurate. The provision of any false or fraudulent information is strictly prohibited.</p>

                        <p>You further consent to receive communications from us electronically. We may communicate with you a variety of ways, such as by e-mail, in-app push notifications, or by notices and messages on the Site. You may revoke your consent to any individually targeted communications at any time.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">1. Your Agreement</h3>
                        <p>1.1 The Teeko Group, that’s us, is made up of –</p>
                        <p>1.1.1 Asia Success Resources Company, a company registered in Malaysia (company registration number 803432-K) with a registered office in the heart of Selangor at No.9 Street Wing, Sunsuria Avenue, Kota Damansara PJU5, Petaling Jaya 47810 Selangor, Malaysia.; and</p>
                        <p>1.1.2 Please read these Terms of Service carefully. By using the Service (as defined below), you agree that you have read and understood the terms in these Terms of Service which are applicable to you. These Terms of Service and the Teeko Policies (as defined below) constitute a legally binding agreement (“Agreement”) between you and Teeko (as defined below). The Agreement applies to your use of the Service provided by Teeko. If you do not agree to the Terms of Service please do not use or continue using the Platform (as defined below) or the Service.</p>

                        <p>1.2 Please read these Terms of Service carefully. By using the Service (as defined below), you agree that you have read and understood the terms in these Terms of Service which are applicable to you. These Terms of Service and the Teeko Policies (as defined below) constitute a legally binding agreement (“Agreement”) between you and Teeko (as defined below). The Agreement applies to your use of the Service provided by Teeko. If you do not agree to the Terms of Service please do not use or continue using the Platform (as defined below) or the Service.</p>

                        <p>1.3 Teeko may amend the terms in the Agreement at any time. Such amendments shall be effective once they are posted on https://teeko.ai or the Application. It is your responsibility to review the Terms of Service and Teeko Policies regularly. Your continued use of the Service after any such amendments, whether or not reviewed by you, shall constitute your agreement to be bound by such amendments.</p>

                        <p>Through our website https://teeko.ai (we will call this, our “website”) and iOS and Android mobile applications (we will call these, our “apps”), you can check timetables and ticket prices for coach or bus journey, buy Discount Cards and book tickets directly (we will call this, our “booking service”). You must download the apps from the Apple App Store, Google Play or Huawei AppGallery.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">1.4 Definition</h3>
                        <p>In these Terms of Service, the following words shall have the meanings ascribed below:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>1.4.1 “Application”</strong> means the relevant mobile application(s) made available for download by Teeko (or its licensors) to Consumers and Partners respectively;</li>
                            <li><strong>1.4.2 “Consumer” or “User”</strong> means any end-user who accesses or uses the Platform to search for and obtain the Solutions;</li>
                            <li><strong>1.4.3 “Consumer Charges” or “User Charges”</strong> means charges incurred by Consumers for the Solutions obtained through the use of the Service, including any applicable tolls, taxes and any other fees or charges that may be due for a particular use of the Service or Solutions;</li>
                            <li><strong>1.4.4 “Teeko” / “We”</strong> means:
                                <ul className="list-[circle] pl-5 mt-2">
                                    <li>1.4.4.1 Asia Success Resources, …</li>
                                    <li>1.4.4.2 the relevant subsidiary, affiliate, associated company of or entity jointly</li>
                                </ul>
                            </li>
                            <li><strong>1.4.5 “Teeko Policies”</strong> means the following:
                                <ul className="list-[circle] pl-5 mt-2">
                                    <li>1.4.5.1 the Privacy Policy;</li>
                                    <li>1.4.5.2 the Driver Partner Code of Conduct or the Teeko’s Consumer Code of Conduct may be applicable; and</li>
                                    <li>1.4.5.3 all other forms, policies, notices, guidelines, frequently asked questions (FAQs), or agreements provided to or entered into by you from time to time;</li>
                                </ul>
                            </li>
                            <li><strong>1.4.6 “Partner”</strong> means the independent third parties (who are not Teeko) who provide the relevant Solutions to Consumers through the Service, including (a) driver-partners, transport service-partners, (b) merchant-partners, and (c) any other relevant goods and services providers;</li>
                            <li><strong>1.4.7 “Personal Data”</strong> is any information which can be used to identify you or from which you are identifiable. This includes but is not limited to your name, nationality, telephone number, bank and credit card details, personal interests, email address, your image, government-issued identification numbers, biometric data, race, date of birth, marital status, religion, health information, vehicle and insurance information;</li>
                            <li><strong>1.4.8 “Platform”</strong> means the Application, Software and any other platform, portal or website which Teeko owns, operates or otherwise makes available to Consumers and/or Partners for the purposes of or in connection with the Service and/or Solutions;</li>
                            <li><strong>1.4.9 “Privacy Policy”</strong> means our privacy policy accessible at: “https://teeko.ai/my/terms-policies/privacy-notice/” as amended from time to time;</li>
                            <li><strong>1.4.10 “Service”</strong> means the linking of Consumers to Partners or other Consumers through the Application, Platform and/or Software;</li>
                            <li><strong>1.4.11 “Solutions”</strong> means the transportation, food and beverage, groceries, logistics and/or other products and services which are made available to Consumers through the following offerings:</li>
                            <li><strong>1.4.12</strong> Any such other services which Teeko may make available from time to time; and</li>
                            <li><strong>1.4.13 “You”</strong> refers to the Partner and/or Consumer as may be applicable.</li>
                        </ul>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">2. Representations, Warranties and Undertakings</h3>
                        <p>2.1 By using the Service and/or Platform, you represent, warrant and undertake that:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>2.1.1 You must be at least sixteen (16) years of age to use the Service. By agreeing to these Terms, you represent and warrant to us: (i) that you are at least sixteen (16) years of age; and (ii) if the User of the Services is under the age of sixteen (16) or is under the age of legal eligibility and capacity in the jurisdiction applicable to such User you hereby confirm that you are the legal guardian of the User and both you and the User have read and agreed to these Terms and approved of the User’s continued use of the Service subject to these Terms; (iii) that you have not previously been suspended or removed from the Service; and (iii) that your use of the Service is in compliance with any and all applicable laws and regulations.</li>
                            <li>2.1.2 You have legal capacity to enter into the Agreement and that you are at least eighteen (18) years old. You cannot enter into the Agreement if you are below eighteen (18) years old;</li>
                            <li>2.1.3 You will provide true, accurate, not misleading, current and complete information as required for the Service and undertake the responsibility to maintain and update your information in a timely manner to keep it true, accurate, not misleading, current and complete at all times during the term of the Agreement. You agree that Teeko may rely on your information as true, accurate, not misleading, current and complete. You acknowledge that if your information is untrue, inaccurate, misleading, not current or incomplete in any respect, Teeko has the right but not the obligation to terminate this Agreement and your use of the Service at any time with or without notice;</li>
                            <li>2.1.4. You will provide us with whatever proof of identity or any other documents, permits, licenses or approvals which we may reasonably request or require;</li>
                            <li>2.1.5 You acknowledge and agree that only one (1) account can be registered on one device, except as otherwise permitted by Teeko;</li>
                            <li>2.1.6 You will only use the Website & Application, Platform and Service for their intended and lawful purposes;</li>
                            <li>2.1.7 You will keep your account password or any identification we provide you which allows access to the Service secure and confidential;</li>
                            <li><strong>2.1.8</strong> You will not authorize others to use your identity or user status, and you may not assign or otherwise transfer your user account to any other person or entity;</li>
                            <li><strong>2.1.9</strong> When using the Service/Platform, you agree to comply with all laws applicable to you and/or your use of the Service/Platform;</li>
                            <li><strong>2.1.10</strong> You agree to notify us immediately of any unauthorized use of your account or any other breach of security;</li>
                            <li><strong>2.1.11</strong> You will not try to interrupt, impair or harm the Service and/or Platform in any way, and shall refrain from: (a) sending spam or otherwise duplicative or unsolicited messages; (b) sending, posting or storing infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including but not limited to materials harmful to children, violative of any third party rights or otherwise in breach of the applicable laws and/or Teeko Policies (c) sending material containing software viruses, worms, trojan horses or other harmful computer code, files, scripts, agents or programs; (d) interfering with or disrupt the integrity or performance of the Platform or the data contained therein; (e) attempting to gain unauthorized access to the Platform or its related software, systems or networks; (f) impersonating any person or entity or otherwise misrepresent your affiliation with a person or entity; (g) engaging in any conduct that could possibly damage our reputation or amount to being disreputable; (h) circumventing the proper operation of the Platform and network which the Service operates on; and (i) using any manual or automated program or script, including but not limited to web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, to unduly burden or hinder the operation and/or performance of the Platform, or to circumvent the navigational structure or presentation of the Platform or its content;</li>
                            <li><strong>2.1.12</strong> You will not attempt to commercially exploit any part of the Website & Application without our permission. For the avoidance of doubt, you are not permitted to modify or make derivative works based on the Platform, its content or any part thereof in any way, or copy, reproduce, publicly display, distribute or otherwise use or communicate them for any public or commercial purpose save where specifically permitted in writing by Teeko. This includes without limitation not to:
                                <ul className="list-[circle] pl-5 mt-2">
                                    <li>a) create or compile, directly or indirectly, any collection, compilation or other directory from any content displayed on the Platform except for your personal, non-commercial use;</li>
                                    <li>b) copy any content displayed through the Platform or “mirror” the Platform or any parts thereof on any other server or wireless or internet-based device, including reproducing any third party product content and reviews, for republication in any format or media; or navigational structure or presentation of the Platform or its content elsewhere;</li>
                                    <li>c) conduct data mining or scraping activities; and</li>
                                    <li>d) disassemble, decompile, reverse engineer, decrypt or attempt to derive and code or extract software from, the Platform or any software or services made available on or through the Platform;</li>
                                </ul>
                            </li>
                            <li><strong>2.1.13</strong> You will not utilize modified devices or applications with the intent of evading detections or facilitating any activities intended to defraud Teeko or to disrupt the natural functions of the Website & Application;</li>
                            <li><strong>2.1.14</strong> You will not use the Website & Application and/or the Software to cause nuisance or behave in an inappropriate or disrespectful manner towards Teeko, Asia Success Resources, or any third party;</li>
                            <li><strong>2.1.15</strong> You will provide accurate, current and complete information as required for the Service and undertake the responsibility to maintain and update your information in a timely manner to keep it accurate, current and complete at all times during the term of the Agreement. You agree that Teeko may rely on your information as accurate, current and complete. You acknowledge that if your information is untrue, inaccurate, not current or incomplete in any respect, Teeko has the right but not the obligation to terminate this Agreement and your use of the Service at any time with or without notice;</li>
                            <li><strong>2.1.16</strong> You will only use an access point or data account which you are authorized to use;</li>
                            <li><strong>2.1.17</strong> You agree that the Service is provided on a reasonable effort basis;</li>
                            <li><strong>2.1.18</strong> You agree that your use of the Service will be subject to Teeko’s Privacy Policy;</li>
                            <li><strong>2.1.19</strong> You agree to assist Teeko with any internal or external investigations as may be required by Teeko in complying with any prevailing laws or regulations in place;</li>
                            <li><strong>2.1.20</strong> You agree to assume full responsibility and liability for all loss or damage suffered by yourself, Teeko or any other party as a result of your breach of this Agreement;</li>
                            <li><strong>2.1.21</strong> You provide us the phone numbers of Teeko users and other contacts in your mobile phone address book on a regular basis. You confirm that you are authorized to provide us with such numbers to enhance your use of the Service.</li>
                            <li><strong>2.1.22</strong> You are aware that when requesting Solutions by SMS or by using the Service or accessing the Platform, standard telecommunication charges will apply;</li>
                            <li><strong>2.1.23</strong> You agree that Teeko may, based on its sole discretion, consider an account to be dormant if there has been no transaction made by you on your user account for a period of six (6) months from the last date of transaction and deactivate or restrict access to your user account; and</li>
                            <li><strong>2.1.24</strong> You agree to assume full responsibility and liability for all loss or damage suffered by yourself, Teeko or any other party as a result of your breach of this Agreement.</li>
                        </ul>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">2.2 Partner Representations</h3>
                        <p>If you are a Partner, you further represent, warrant, and undertake that:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>2.2.1</strong> If applicable, you or your employed drivers shall possess a valid driver’s license, and for airport transfer, taxi and bus services that is approved by Agensi Pengakutan Awan Darat (“APAD”), a public vehicle service license (“PSV License”) in order to operate a motor vehicle and have all the appropriate licenses, approvals, permits, consents, authority and mandatory insurance policies related to or in connection with your provision of the Solution(s) in the jurisdiction in which you use the Service;</li>
                            <li><strong>2.2.2</strong> If applicable, you own, or have the legal right and authority to operate, the vehicle, equipment, premises or any other matter or thing which is involved or used in the course of your provision of the Solution(s);</li>
                            <li><strong>2.2.3</strong> If applicable, you have a valid policy/ies of liability insurance (in industry-standard coverage amounts in connection with your provision of the Solution(s));</li>
                            <li><strong>2.2.4</strong> If applicable, you possess a valid policy of private vehicle insurance and relevant insurance (in industry-standard coverage amounts) to operate the vehicle as required by the relevant authorities and any other applicable regulation for the operation of the vehicle...</li>
                            <li><strong>2.2.5</strong> You shall be solely responsible for any and all claims, judgments and liabilities resulting from any accident, loss or damage including, but not limited to, personal injuries, death, total loss and property damage which is due to or is alleged to be a result of the Solution(s)provided by you;</li>
                            <li><strong>2.2.6</strong> You shall obey all local laws related to your provision of the Solution(s) and will be solely responsible for any violations of such local laws and you acknowledge that Teeko has the right to carry out background search on you from time to time, to ensure that you are not directly or indirectly involved in a criminal action or being investigated for a criminal allegation or implicated in a criminal proceeding;</li>
                            <li><strong>2.2.7</strong> You shall not contact Consumers for purposes other than in connection with the Service;</li>
                            <li><strong>2.2.8</strong> You shall not reverse look-up, trace or seek to trace any information on any other user of or visitor to the Website & Application, or any Consumers, including without limitation any user account not owned by you, to its source, or exploit the Website & Application or any service or information made available or offered by or through the Website & Application, in any way where the purpose is to reveal any information, including but shall not be limited to personal identification information, other than your own information, as provided for by the Website & Application</li>
                            <li><strong>2.2.9</strong> You are aware that when responding to Consumers, standard telecommunication charges may apply which shall be solely borne by you;</li>
                            <li><strong>2.2.10</strong> If you are required to and do sign up for an account on behalf of your employer, your employer shall be the owner of the account, and you represent and warrant that you have the authority to bind your employer to the Agreement;</li>
                            <li><strong>2.2.11</strong> You are strictly forbidden to use the Service for other purposes such as but not limited to data mining of Teeko’s information or information related to the Website & Application or the Service. A breach hereof constitutes a grave offence and may be treated as industrial espionage or sabotage, and Teeko, Asia Success Resources reserves the right to take such action as may be appropriate or permitted under the law against you, and/or any person, whether natural or artificial, directing or instructing you, in the event you use the Service other than for the purpose for which it is intended to be used; and</li>
                            <li><strong>2.2.12</strong> Without prejudice to any other provisions, information which you have submitted to us for your registration as a Partner on the Platform, which may include your personal data as described in the Privacy Policy, may be linked to the account on the Platform or otherwise be temporarily displayed in the course of the Services on the Platform. You hereby give your consent to such use of information for the purposes of the Solutions, and to facilitate your use of the Platform. Your use of the Platform or any part thereof may be monitored by us or a third-party service provider to provide you with information on your business and account as well as better services. You further agree that any personal data you receive via the Platform or otherwise in connection with the Solutions shall only be used for the direct and specific purpose for which you are originally provided the personal data and such personal data shall be deleted or anonymized once the personal data is no longer required to be retained for the said purpose. For the avoidance of doubt, when you are provided with the personal data of a Consumer via the Platform for the purposes of obtaining prior confirmation to amend an order placed, you shall only use the personal data provided for that sole purpose and remove it as soon as you no longer need the data for that purpose.</li>
                        </ul>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">2.3 Consumer Representations</h3>
                        <p>If you are a Consumer, you further represent, warrant and undertake that :</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>2.3.1</strong> Your use of the Service is for your own sole, personal use or, where permitted, for the use of another person who is at least twelve (12) years old (“Unaccompanied Minor”), in which case you shall assume primary responsibility of the Unaccompanied Minor;</li>
                            <li><strong>2.3.2</strong> You will not use the Website & Application, Platform and/or the Software to cause nuisance, annoyance, inconvenience or make fake bookings;</li>
                            <li><strong>2.3.3</strong> Where applicable, you agree to indicate the accurate number of passenger(s) when requesting for the Service. You further acknowledge and agree that if the information on the number of passengers is untrue or inaccurate, the Partner is entitled to cancel your booking and you may be charged a Cancellation Fee.</li>
                            <li><strong>2.3.4</strong> You shall not contact the Partner for purposes other than the Service;</li>
                            <li><strong>2.3.5</strong> You shall not intentionally or unintentionally cause or attempt to cause damage to the Partner or any property of the Partner.</li>
                        </ul>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">3. Use of our services</h3>
                        <p>3.1 You’ll have to pay for any costs involved with accessing our booking service (for example, internet access fees and mobile data costs). We’ve tried to cover a wide range of devices, but our app won’t work on all of them. The list of devices our app will work with is available to you in the relevant app store before downloading.</p>
                        <p>3.2 We’re an official agent on behalf of train, coach and bus operators (the operators), but we don’t run these services ourselves. We’re only responsible for our booking service, to the extent laid out in these Terms and Conditions. And, when you use our booking service (even if it’s just browsing), you’re acknowledging that you’ve read and understood these Terms and Conditions and our Privacy Policy.</p>
                        <p>3.3 We will give you the key information on the tickets we sell, so you can make an informed choice. Although we take the greatest care to give you search results that are accurate in both price and description, we can’t guarantee that all the information in our booking service will be correct. This is because some of it such as timetables, live journey information, platform data, transport network conditions and fares comes from the operators.</p>
                        <p>3.4 All operators have different pricing systems, which means that prices may change between the time we show them to you as a search result and your final page before payment. But, we’ll let you know before you pay if the price has changed.</p>
                        <p>3.5 You can apply loyalty and/or discount cards for eligible passengers via our booking service. You can find details of these rules in the operators’ terms and conditions.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">4. Compatibility</h3>
                        <p>Different models or versions of routers, browsers and devices may have firmware or settings that are not compatible with the Website, Application, Platform and Software. While we continuously develop the Website, Application, Platform and Software in order to, as far as possible, support all commonly used devices and models in markets and all browsers where the Website, Application, Platform and Software is likely to be accessed from, we do not warrant compatibility of the Website, Application, Platform and Software with specific mobile devices or other hardware.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">5. License Grant and Restrictions</h3>
                        <p>5.1 Teeko and its licensors, where applicable, grant you a revocable, non-exclusive, non- transferable, limited license to use and access the Website, Application and/or the Software to use the Service, subject to the terms and conditions of this Agreement. All rights not expressly granted to you are reserved by Teeko and its licensors.</p>
                        <p>5.2 You shall not:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>5.2.1</strong> post, distribute or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior consent of the owner of such proprietary rights; or</li>
                            <li><strong>5.2.2</strong> remove any copyright, trademark or other proprietary rights notices contained on the Website, Application or Platform.</li>
                        </ul>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">6. Payments</h3>
                        <h4 className="text-lg font-bold text-gray-900 dark:text-white mt-4">6.1 Payment Terms for Partners (Drivers-partners / Transport Operators)</h4>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>6.1.1</strong> Teeko charges a fee for your use of the Service (“Service Fee”). The Service Fee may be up to 15% of the Consumer Charges unless otherwise communicated to and accepted by you before you commence provision of the Solution(s). The Service Fees are payable by you immediately and are non-refundable. This no-refund policy shall apply at all times regardless of your decision to terminate your access to the Website/ Application / Platform, our decision to terminate or suspend your access to the Website/ Application / Platform, disruption caused to the Service whether planned, accidental or intentional, or any reason whatsoever.</li>
                            <li><strong>6.1.2</strong> YOU ACKNOWLEDGE AND CONFIRM THAT Teeko MAY ADMINISTER AND ACT AS YOUR COLLECTION AGENT TO PAY TO YOU THE TOTAL AMOUNT OF CONSUMER CHARGES DUE TO YOU IN RESPECT OF YOUR PROVISION OF THE SOLUTION.</li>
                            <li><strong>6.1.3</strong> Teeko retains the right to suspend the processing of any transaction where it reasonably believes that the transaction may be fraudulent, illegal or involves any criminal activity or where you and/or the Consumer have breached any of the Terms in this Agreement. In such an event, you shall not hold Teeko liable for any withholding of, delay in, suspension, forfeiture or cancellation of, any payment(s) to you.</li>
                            <li><strong>6.1.4</strong> Teeko may, at its sole discretion, make promotional offers with different features and different rates on the Solutions to any of the Consumer whereby these promotional offers shall accordingly be honored by you. Teeko may change the Service Fee at any time at its sole discretion.</li>
                        </ul>
                        <h4 className="text-lg font-bold text-gray-900 dark:text-white mt-4">6.2 Payment Terms for Consumers:</h4>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>6.2.1</strong> Consumers are required to make full payment of the Consumers Charges for all services offered in the Website & Application by the method selected at the time of booking, which may be cash, or one of the automated payment methods available to you on the Website & Application. Any payment pursuant to such selection is non-refundable and irrevocable.</li>
                            <li><strong>6.2.2</strong> Automated payment may be made by credit card and or debit card, by GrabPay, Touch n Go, alternative e-Wallets or by PayLater or where available by such other methods as are made available in the website and application.</li>
                            <li><strong>6.2.3</strong> If the tipping feature is available, you may have the option to pre-set a default “tip” amount of your choosing when you register for the Service. This will automatically be included in the Consumer Charges after the Solution has been provided and given to the Partners unless you choose to change the amount or remove the tip.</li>
                            <li><strong>6.2.4</strong> We will also charge You with additional fees for using certain payment methods as stated by the applicable laws, i.e. if You use a corporate card or a tripartite system (American Express or Diners). These fees are non-refundable. Please note that Our systems automatically detect the payment method which is actually used by You and the corresponding additional fees are charged, if any.</li>
                        </ul>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">7. Refund Policy for changes or cancellations and Service Fees</h3>
                        <p>7.1 Depending on the third-party provider and fare type, you may be able to either cancel and get a refund for your ticket or change your ticket online, via Help Center , or directly with the third-party provider. We will generally inform you of the main conditions during the booking flow, but we strongly advise you to read and understand the third-party terms and conditions before completing your booking.</p>
                        <p>7.2 You may need to pay for any difference in cost for your new ticket and any applicable fees determined by the third-party providers. In addition, if you decide to change or cancel your ticket through our Help Center , Teeko may charge you a fee for changes or cancellations for the service performed by our Customer Service team. Please note that our service fees do not include the amounts eventually charged by the third-party providers, according to their terms and conditions. Teeko service fees are non-refundable.</p>
                        <p>7.3 Changes or cancellations processed through our Help Center may only be guaranteed, if your request is submitted at least 24 hours prior to the departure time of your trip. Please keep in mind that this is always subject to the terms and conditions of the corresponding third-party provider, which may be more restrictive. We will facilitate the communication of your request to the respective bus operator and inform you of the outcome. Upon approval from the bus operator, refunds will be processed within 30 business days and credited to the original method of payment.</p>
                        <p>7.4 Some tickets, especially those sold at promotional or discounted rates, may be non-refundable as per the operator’s policy.</p>
                        <p>7.5 In cases where a bus operator cancels a service or significantly changes a schedule, customers may be entitled to a full refund subject to insurance policy acquired with us or alternative arrangements, in accordance with the operator policy.</p>
                        <p>7.6 We won’t change, cancel, replace or refund fraudulent tickets.</p>
                        <p>7.7 This policy is in alignment with Malaysian consumer protection laws. Teeko AI reserves the right to amend this refund policy, and customers are encouraged to review it regularly.</p>
                        <p>For further assistance or clarification regarding our refund policy or the policies of specific bus operators, please do not hesitate to contact us.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">8. How to contact us</h3>
                        <p>8.1 Email us</p>
                        <p>Fill out an online form with as much detail as possible, so we can get your query to the right person and give you the best answer. We ll aim to get back to you within one day.</p>
                        <p>8.2 Give us a call</p>
                        <p>Teeko is operated by Asia Success Resources. Registration number (803432-K). To contact us, please contact Teeko Customer Care at +011 5587 2981.</p>
                        <p>Call us between 08:00 and 18:00 Malaysia time any day of the week to make a booking or to get help with existing bookings.</p>
                        <p>Just so you know, we can only discuss booking details with the person who made the booking, for data protection reasons. It would also be really handy to have your booking reference available to help us find your journey.</p>
                        <p>We also offer support by email and we ll aim to get back to you within one day. (support@teeko.ai)</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">9. Ratings and Complainants</h3>
                        <h4 className="text-lg font-bold text-gray-900 dark:text-white mt-4">9.1 Ratings</h4>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>9.1.1</strong> Consumers and Partners may be allowed to rate each other in respect of Solutions provided.</li>
                            <li><strong>9.1.2</strong> Every rating will be automatically logged onto Teeko’s system and Teeko may analyse all ratings received. Teeko may take all appropriate actions including suspending your use of the Service without any notice or compensation to you.</li>
                        </ul>
                        <h4 className="text-lg font-bold text-gray-900 dark:text-white mt-4">9.2 Complainants</h4>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>9.2.1</strong> Any complaints between Partners and Consumers must be taken up with each other directly.</li>
                            <li><strong>9.2.2</strong> Please contact our Help Center if you have any questions or comments in relation to the Platform.</li>
                        </ul>
                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">10. Repairs and cleaning fees for consumers</h3>
                        <p>10.1 Where applicable, you shall be responsible for the cost of repairing any damage to or necessary cleaning of the Partner’s property as a result of your misuse of the Service or breach of the Terms of Service herein. Teeko may facilitate payment for reasonable cost of such repair or cleaning on behalf of the Partner via your designated payment method or demand from you in cash, in the event a request for repair or cleaning request by the Partner has been verified by Teeko</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">11. Intellectual Property Ownership</h3>
                        <p>11.1 Teeko and its licensors, where applicable, shall own all right, title and interest, including all related intellectual property rights, in and to the Platform and by extension, the Service as well as any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the same. The Terms of Service do not constitute a sale agreement and do not convey to you any rights of ownership in or related to the Service, the Platform, or any intellectual property rights owned by Teeko and/or its licensors. Teeko’s name, Teeko’s logo, the Service, the Platform and the third party transportation providers’ logos and the product names associated with the Platform are trademarks of Teeko or third parties, and no right or license is granted to use them. For the avoidance of doubt, the term the Platform herein shall include its respective components, processes and design in its entirety.</p>
                        <p>11.2 You may be able to submit your content publicly available via or otherwise in relation to certain feature(s) of the Platform. Save where otherwise specified in the Agreement, Teeko does not claim ownership of the content that you provide us with. Where you upload or provide us with any content that is covered by intellectual property rights, you (a) irrevocably grant Teeko a royalty-free, worldwide, perpetual, non-exclusive, unrestricted right and license to host, store, use, reproduce, modify, edit, adapt, translate, create derivative works of, publish, publicly perform or display, distribute, sublicense, or otherwise provide to others, your content (including without limitation name and/or likeness) in any and all media, formats, and channels (now in existence or hereinafter developed) for any purpose; and (b) undertake that you have the right to grant us such license and shall remain responsible for the content you provided. For the avoidance of doubt, you also grant to Teeko the right (though you acknowledge and agree that Teeko shall not be so obliged) to use your name and/or likeness in connection with the submitted materials and other information as well as in connection with all advertising, marketing and all promotional material related thereto. If you choose to give us feedback, such as suggestions to improve our services, we may act on your feedback without obligation to you. Should you wish to request removal of any of the content, you may contact Teeko’s Help Centre to submit such request. Where the content you submitted is a review, the Review Guideline shall additionally apply.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">12. Taxes</h3>
                        <p>12.1 You shall maintain in confidence all information and data relating to Teeko, its services, products, business affairs, marketing and promotion plans or other operations and its associated companies which are disclosed to you by or on behalf of Teeko (whether orally or in writing and whether before, on or after the date of this Agreement) or which are otherwise directly or indirectly acquired by you from Teeko, or any of its affiliate companies, or created in the course of this Agreement. You shall further ensure that you only use such confidential information in order to use the Service, and shall not without Teeko’s prior written consent, disclose such information to any third party nor use it for any other purpose.</p>
                        <p>12.2 The above obligations of confidentiality shall not apply to the extent that you can show that the relevant information:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>12.2.1.</strong> was at the time of receipt already in your possession;</li>
                            <li><strong>12.2.2.</strong> is, or becomes in the future, public knowledge through no fault or omission on your part;</li>
                            <li><strong>12.2.3.</strong> was received from a third party having the right to disclose it; or</li>
                            <li><strong>12.2.4.</strong> is required to be disclosed by law.</li>
                        </ul>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">13. Data Privacy and Personal Data Protection Policy</h3>
                        <p>13.1 Teeko collects and processes your Personal Data in accordance with its Privacy Policy. The Privacy Policy applies to all of Teeko’s Services and its terms are made a part of this Agreement by this reference.</p>
                        <p>13.2 Where applicable, you agree and consent to Teeko, its subsidiaries and any of its affiliate companies collecting, using, processing and disclosing Personal Data as further described in our Privacy Policy.</p>
                        <p>13.3 You acknowledge that Teeko may disclose Personal Data of other individuals to you in the course of your use of Teeko’s Services. You represent and warrant that you will only use such Personal Data for the purpose for which it was disclosed to you by Teeko, and not for any other unauthorized purposes.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">14. Indemnification</h3>
                        <p>14.1 By agreeing to the Terms of Service upon using the Service, you agree that you shall indemnify and hold Teeko, its licensors and each such party’s affiliates, officers, directors, members, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys’ fees and costs and/or regulatory action) arising out of or in connection with: (a) your use of the Service, the Platform, Software and/or the Application in your dealings with the Partners or Consumers (as the case may be), third party merchants, providers, partners, advertisers and/or sponsors, or (b) your violation or breach of any of the Terms of Service, any third party terms and conditions or any applicable law or regulation, whether or not referenced herein, or (c) your violation of any rights of any third party, including Partners or Consumers arranged via the Service, or (d) your use or misuse of the Service, the Platform, Software and/or the Application; and (e) where applicable your ownership, use or operation of any property, including your provision of Solutions to Consumers via the Service.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">15. Disclaimer of Warranties</h3>
                        <p>15.1 The Application, its content and any related service(s) is provided to you on an “as is” basis. Teeko makes no representations or warranties of any kind, express or implied, in connection with the Software, Application, Platform, Service, these Terms of Service, the content or any related service(s). Although we make reasonable efforts to keep the Application up-to-date, we make no representations, warranties or guarantees, whether express or implied, that such information is accurate, complete or up to date. We shall not be liable for any direct, indirect or consequent loss arising from the modifications or amendments to the Software, Application, Platform, Service, or Terms of Service.</p>
                        <p>15.2 Teeko makes no representation or warranty of any kind whatsoever, express or implied, in respect of Solutions provided by Partners or any Solutions procured through the use of the Service. You agree that you shall bear all risk arising out of your use of the Service and any Solution provided by Partners and shall have no recourse to Teeko in respect of the same.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">16. Third Parties Interactions</h3>
                        <p>16.1 During use of the Service, you may enter into correspondence or transactions with third parties who display or offer their goods and/or service through the Platform or Application. Any such communication or agreement is strictly between you and the applicable third party and Teeko and its licensors shall have no liability or obligation for any such communication or agreement. Neither Teeko nor any of its affiliate companies endorses any applications or sites on the Internet that are linked through the Platform or Application, and in no event shall Teeko, its licensors or its affiliate companies be responsible for any content, products, services or other materials on or available from such sites or Partners. Certain Partners of transportation, goods and/or services may require your agreement to additional or different Terms of Service and privacy policies prior to your use of or access to such goods or services, and Teeko is not a party to and disclaims any and all responsibility and/or liability arising from such agreements between you and the Partners. You acknowledge that such additional or different terms of use and privacy policies may apply to your use of such third party services. Teeko is not liable for any information that you provide to or authorise us to provide to a third party, or for such third party’s collection, use and disclosure of such information.</p>
                        <p>16.2 Teeko may rely on third party advertising and marketing supplied through the Service and other mechanisms to subsidize the Service and/or to earn additional revenue. You agree to receive such advertising and marketing. If you do not want to receive such advertising and marketing, please refer to our Privacy Policy for instructions to unsubscribe or update your privacy settings. You agree and allow Teeko to compile and release information regarding you and your use of the Service on an anonymous basis as part of a consumer profile or similar report or analysis. You agree that it is your responsibility to take all precautions in all actions and interactions with any third party you interact with through the Service and/or advertising or marketing material supplied by third parties through the Service.</p>
                        <p>16.3 We may include hyperlinks to other websites or content on the Internet that are owned or operated by third parties or otherwise display content or material provided by third parties (“Third Party Content“). Such Third Party Content are not under our control and we are not responsible or liable for any errors, omissions, delays, defamation, libel, slander, falsehood, obscenity, pornography, profanity, inaccuracy or any other objectionable material contained in the content, or the consequences of accessing, any linked website. Any hyperlinks to any other websites or content are not an endorsement or verification of such websites or content and you agree that your access to or use of such linked websites or content is entirely at your own risk. Please approach our Help Centre should you have any questions or concerns about any of the Third Party Content.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">17. Internet Delays</h3>
                        <p className="uppercase">THE SERVICE, PLATFORM, WEBSITE, APPLICATION AND/OR THE SOFTWARE MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS INCLUDING THE DEVICE USED BY YOU OR THE Partners BEING FAULTY, NOT CONNECTED, OUT OF RANGE, SWITCHED OFF OR NOT FUNCTIONING. Teeko IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, DAMAGES OR LOSSES RESULTING FROM SUCH PROBLEMS.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">18. Limitation of Liability</h3>
                        <p>18.1 UNLESS OTHERWISE STATED, AND TO THE FULLEST EXTENT ALLOWED BY LAW, ANY CLAIMS AGAINST Teeko BY YOU SHALL BE LIMITED TO THE AGGREGATE AMOUNT OF ALL AMOUNTS ACTUALLY PAID BY AND/OR DUE FROM YOU IN UTILISING THE SERVICE DURING THE EVENT GIVING RISE TO SUCH CLAIMS. Teeko AND/OR ITS LICENSORS SHALL NOT BE LIABLE FOR ANY LOSS, DAMAGE OR INJURY WHICH MAY BE INCURRED BY OR CAUSED TO YOU OR TO ANY PERSON FOR WHOM YOU HAVE BOOKED THE SERVICE OR SOLUTION, INCLUDING BUT NOT LIMITED TO:</p>
                        <ul className="list-disc pl-5 space-y-2 uppercase">
                            <li>18.1.1 LOSS, DAMAGE OR INJURY ARISING OUT OF, OR IN ANY WAY CONNECTED WITH THE SERVICE, THE PLATFORM, WEBSITE, APPLICATION AND/OR THE SOFTWARE;</li>
                            <li>18.1.2. THE USE OR INABILITY TO USE THE SERVICE, THE PLATFORM, THE WEBSITE, APPLICATION AND/OR THE SOFTWARE;</li>
                            <li>18.1.3. ANY RELIANCE PLACED BY YOU ON THE COMPLETENESS, ACCURACY OR EXISTENCE OF ANY ADVERTISING;OR</li>
                            <li>18.1.4. AS A RESULT OF ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY CONSUMER, PARTNER, MERCHANT, ADVERTISER OR SPONSOR WHOSE ADVERTISING APPEARS ON THE WEBSITE OR IS REFERRED TO BY THE SERVICE, THE WEBSITE, THE APPLICATION AND/OR THE SOFTWARE,</li>
                            <li>EVEN IF Teeko AND/OR ITS LICENSORS HAVE BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</li>
                        </ul>
                        <p>18.2 Teeko DOES NOT WARRANT AND REPRESENT THAT IT ASSESSES OR MONITORS THE SUITABILITY, LEGALITY, ABILITY, MOVEMENT OR LOCATION OF ANY CONSUMERS OR PARTNERS INCLUDING MERCHANTS, ADVERTISERS AND/OR SPONSORS AND YOU EXPRESSLY WAIVE AND RELEASE Teeko FROM ANY AND ALL LIABILITY, CLAIMS OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO THE CONSUMERS OR PARTNERS INCLUDING THIRD PARTY TRANSPORTATION PROVIDERS, MERCHANTS, ADVERTISERS AND/OR SPONSORS.</p>
                        <p>18.3 Teeko WILL NOT BE A PARTY TO DISPUTES, OR NEGOTIATIONS OF DISPUTES BETWEEN YOU AND CONSUMERS OR AND PARTNERS INCLUDING MERCHANTS, ADVERTISERS AND/OR SPONSORS. UNLESS YOU ARE A CORPORATE CONSUMER WITH A CURRENT CORPORATE ACCOUNT WITH Teeko, Teeko CANNOT AND WILL NOT PLAY ANY ROLE IN MANAGING PAYMENTS BETWEEN YOU AND THE PARTNERS, INCLUDING MERCHANTS, ADVERTISERS AND/OR SPONSORS. RESPONSIBILITY FOR THE DECISIONS YOU MAKE REGARDING SERVICES AND PRODUCTS OFFERED VIA THE SERVICE, THE SOFTWARE, THE WEBSITE AND/OR THE APPLICATION (WITH ALL ITS IMPLICATIONS) RESTS SOLELY WITH AND ON YOU. YOU EXPRESSLY WAIVE AND RELEASE Teeko FROM ANY AND ALL LIABILITY, CLAIMS, CAUSES OF ACTION, OR DAMAGES ARISING FROM YOUR USE OF THE SERVICE, THE SOFTWARE, THE WEBSITE AND/OR THE APPLICATION, OR IN ANY WAY RELATED TO THE THIRD PARTIES INCLUDING THIRD PARTY TRANSPORTATION PROVIDERS, MERCHANTS, ADVERTISERS AND/OR SPONSORS INTRODUCED TO YOU BY THE SERVICE, THE SOFTWARE, THE WEBSITE AND/OR THE APPLICATION.</p>
                        <p>18.4 THE QUALITY OF THE SOLUTIONS SCHEDULED THROUGH THE USE OF THE SERVICE IS ENTIRELY THE RESPONSIBILITY OF THE PARTNERS WHO ULTIMATELY PROVIDES SUCH SOLUTION TO CONSUMERS. YOU UNDERSTAND, THEREFORE, THAT BY USING THE SERVICE, YOU MAY BE EXPOSED TO TRANSPORTATION THAT IS POTENTIALLY DANGEROUS, OFFENSIVE, HARMFUL TO MINORS, UNSAFE OR OTHERWISE OBJECTIONABLE, AND THAT YOU USE THE SERVICE AT YOUR OWN RISK.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">19. Notice</h3>
                        <p>19.1 Teeko may give notice through the Website, Application, electronic mail to your email address in the records of Teeko, or by written communication sent by registered mail or pre-paid post to your address in the record of Teeko. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by registered mail or pre-paid post) or 1 hour after sending (if sent by email). You may give notice to Teeko (such notice shall be deemed given when received by Teeko) by letter sent by courier or registered mail to Teeko using the contact details as provided in the Website and Application.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">20. Assignment</h3>
                        <p>20.1. This Terms of Service as modified from time to time may not be assigned by you without the prior written approval of Teeko but may be assigned without your consent by Teeko. Any purported assignment by you in violation of this section shall be void.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">21. Dispute Resolution</h3>
                        <p>21.1. This Terms of Service shall be governed by Malaysian law, without regard to the choice or conflicts of law provisions of any jurisdiction, and any disputes, actions, claims or causes of action arising out of or in connection with this Terms of Service or the Service shall be referred to the Asian International Arbitration Centre (“AIAC”), in accordance with the Rules of the AIAC as modified or amended from time to time (the “Rules”) by a sole arbitrator appointed by the mutual agreement of you and Teeko (the “Arbitrator”). If you and Teeko are unable to agree on an arbitrator, the Arbitrator shall be appointed by the President of AIAC in accordance with the Rules. The seat and venue of the arbitration shall be Kuala Lumpur, in the English language and the fees of the Arbitrator shall be borne equally by you and Teeko, provided that the Arbitrator may require that such fees be borne in such other manner as the Arbitrator determines is required in order for this arbitration clause to be enforceable under applicable law.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">22. Relationship</h3>
                        <p>22.1. Nothing contained in these Terms of Service shall be construed as creating any agency, partnership, or other form of joint enterprise with Teeko.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">23. Severability</h3>
                        <p>23.1. If any provision of the Terms of Service is held to be invalid or unenforceable, the legality, validity and enforceability of the remaining provisions shall not be affected or impaired.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">24. No Waiver</h3>
                        <p>24.1. The failure of Teeko to enforce any right or provision in the Terms of Service shall not constitute a waiver of such right or provision.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">25. Entire Agreement</h3>
                        <p>25.1. This Agreement comprises the entire agreement between you and Teeko and supersedes any prior or contemporaneous negotiations or discussions.</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">26. Suspension and Termination; Modification of Platform Content</h3>
                        <p>26.1. You agree that we may do any of the following, at any time, without notice: (i) to modify, suspend or terminate operation of or access to the Platform, or any portion of the Platform (including access to your Account and/or the availability of any products or services), for any reason; (ii) to modify or change any applicable policies or terms; and (ii) to interrupt the operation of the Platform or any portion of the Platform (including access to your Account and/or the availability of any products or services), as necessary to perform routine or non-routine maintenance, error correction, or other changes. We shall not be required to compensate you for any suspension or termination.</p>
                        <p>26.2. Without prejudice to any other provisions, we may vary, modify or remove Platform Content without notice (including without limitation information relating to the availability of a product or service, product or service descriptions, pricing, promotions, offers, product shipping charges and transit time). In the event any Platform Content contains any typographical errors, inaccuracies, omissions or otherwise violates Teeko Policies, we reserve the right (but shall not be obliged, save to the extent where mandated by applicable laws) to carry out any such measures as Teeko deems appropriate (collectively, “Rectification Measure”) including without limitation (i) correcting the said errors, inaccuracies or omissions, (ii) changing or updating information; and/or (iii) where applicable, cancelling the affected orders at any time without prior notice (including without limitation after an order has been submitted).</p>

                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8">27. No Third Party Rights or Assignment</h3>
                        <p>This agreement does not give rights to any third parties who are not party to this Agreement.</p>
                    </div>
                </div>
            </main >
            <Footer />
        </div >
    );
}
